name: sys
description: sys project
version: 2025.427.1718
homepage: 
repository: https://github.com/dart-pkg/sys
environment:
  sdk: ^3.7.2
dependencies:
  archive: ^4.0.7
  http: ^1.3.0
  path: ^1.9.1
  std: ^2025.427.52
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.426.2027
  test: ^1.25.15
