name: "sys"
description: "sys project"
version: 2025.426.1427
homepage: null
repository: "https://github.com/dart-pkg/sys"
environment:
  sdk: "^3.7.2"
dependencies:
  archive: ^4.0.7
  http: ^1.3.0
  path: ^1.9.1
  std: ^2025.425.2018
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
