name: sys
description: sys project
version: 2025.502.2255
homepage: 
repository: https://github.com/dart-pkg/sys
environment:
  sdk: ^3.7.2
dependencies:
  archive: ^4.0.7
  debug_output: ^2025.502.2007
  http: ^1.3.0
  path: ^1.9.1
  std: ^2025.502.2210
dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
