name: "sys"
description: "sys project"
version: "2025.422.2227"
homepage: null
repository: "https://github.com/dart-pkg/sys"
environment:
  sdk: "^3.7.2"
dependencies:
  http: ^1.3.0
  path: ^1.9.1
  process_run: ^1.2.4
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.6
  test: ^1.25.15
