name: sys
description: sys project
version: 2025.526.2347
homepage: 
repository: https://github.com/dart-pkg/sys
environment:
  sdk: ^3.7.2
dependencies:
  archive: ^4.0.7
  http: ^1.4.0
  std: ^2025.526.2333
dev_dependencies:
  test: ^1.26.2
  debug_output: ^2025.504.1731
  lints: ^6.0.0
