name: "sys"
description: "sys project"
version: 2025.424.1853
homepage: null
repository: "https://github.com/dart-pkg/sys"
environment:
  sdk: "^3.7.2"
dependencies:
  http: ^1.3.0
  intl: ^0.20.2
  path: ^1.9.1
  std: ^2025.424.1835
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
