name: sys
description: "sys package project"
version: 0.0.3
homepage:
repository: https://github.com/dart-pkg/sys

environment:
  sdk: ^3.7.2

dependencies:
  output: ^1.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
