name: sys
description: sys package project
version: 2025.421.938
homepage:
repository: https://github.com/dart-pkg/sys

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.3.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.5
  test: ^1.25.15
